# Generated by Django 4.2.3 on 2023-08-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father', models.CharField(max_length=100)),
                ('classname', models.IntegerField(max_length=100)),
                ('age', models.IntegerField(max_length=100)),
            ],
        ),
    ]
