# Generated by Django 4.2.3 on 2023-08-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_alter_student_age_alter_student_classname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classname',
            field=models.IntegerField(),
        ),
    ]
