# Generated by Django 4.2.3 on 2023-08-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_alter_student_classname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='classname',
            field=models.IntegerField(max_length=100),
        ),
    ]
