# Generated by Django 4.2.3 on 2023-08-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_alter_student_age_alter_student_classname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.AlterField(
            model_name='student',
            name='classname',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='father',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
